# -*- coding: utf-8 -*-
"""compare_latex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ii51Ywq_4pndEZyb6KiU8zFivyaQCvGn
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def calculate_similarity(file1, file2):
    # Read the files
    with open(file1, 'r', encoding='utf-8') as f1, open(file2, 'r', encoding='utf-8') as f2:
        text1 = f1.read()
        text2 = f2.read()

    # Create a TF-IDF Vectorizer
    vectorizer = TfidfVectorizer()
    vectors = vectorizer.fit_transform([text1, text2])

    # Compute cosine similarity
    similarity = cosine_similarity(vectors[0], vectors[1])[0][0]
    return similarity

def save_report(similarity_score, output_file):
    # Create a report and save it to a text file
    with open(output_file, 'w', encoding='utf-8') as report_file:
        report_file.write("Text Similarity Report\n")
        report_file.write("=======================\n")
        report_file.write(f"File 1: {f1}\n")
        report_file.write(f"File 2: {f2}\n")
        report_file.write(f"Similarity Score: {similarity_score * 100:.2f}%\n")
        report_file.write("=======================\n")

# File paths
f1 = "/content/md10.txt"
f2 = "/content/md9.txt"

# Calculate similarity
similarity_score = calculate_similarity(f1, f2)
print(f"Similarity: {similarity_score * 100:.2f}%")

# Save report to a text file
output_file = "similarity_report.txt"
save_report(similarity_score, output_file)
print(f"Report saved to {output_file}")

def txt_to_latex(input_txt_file, output_tex_file):
    # Read the input text file
    with open(input_txt_file, 'r', encoding='utf-8') as txt_file:
        content = txt_file.read()

    # Create a basic LaTeX structure
    latex_content = r"""
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{geometry}
\geometry{a4paper, margin=1in}

\begin{document}

\section*{Text Content}
""" + content + r"""

\end{document}
"""

    # Write to the output .tex file
    with open(output_tex_file, 'w', encoding='utf-8') as tex_file:
        tex_file.write(latex_content)

    print(f"LaTeX file saved as {output_tex_file}")

# Specify input and output files
input_txt_file = "/content/similarity_report.txt"  # Replace with your .txt file path
output_tex_file = "report_latex.tex"  # Replace with desired .tex file path

# Convert the text file to LaTeX
txt_to_latex(input_txt_file, output_tex_file)